### ISSUE TITLE
How I can add new letter?

### ISSUE THREAD

**Issue by yahyaizhar** [hirofumii/Noto-Sans-CJK-JP.min#3]
Is there any way to add new letter in this font? when I use this font while generating pdf, letter '遞' got missing

**Comment by hiz8** [comment]
Sorry for the delay in replying.

This font set is provided as a subset by me using the following software.

- [Subset font maker(Japanese)](https://opentype.jp/subsetfontmk.htm)
- [WOFF Converter(Japanese)](https://opentype.jp/woffconv.htm)

As you said, "遞" is not included in it, because it is not a common kanji. Because it's a very uncommon kanji.
If you want to include this in this font set, it takes a little bit of work, but you need to do the subseting yourself using their software.
